/**
 * Client-side Bootstrap
 * 
 * The bootstrap is responsible for:
 *  > setting up mediator for routines to use
 *  > load routines set by server
 * 
 */

/* setup mediator */
var mediator = require('./lib/mediator');

/* require all routines
 * list is automatically generated by server
 * do not edit delimiters
 */

/* routines-start */
require('./routines/debug/debug.js');
require('./routines/debug/csio/boot.js');
require('./routines/debug/csio/registration.js');
require('./routines/csio/configurator.js');
require('./routines/csio/connector.js');
require('./routines/csio/csio.js');
require('./routines/csio/registration/register.js');
/* routines-end */

/* boot ready */
mediator.emit('boot.ready');