/**
 * Client-side Bootstrap
 * 
 * The bootstrap is responsible for:
 *  > setting up mediator for routines to use
 *  > load routines set by server
 * 
 */

/* setup mediator */
var mediator = require('./lib/mediator');

/* require all routines
 * list is automatically generated by server
 * do not edit delimiters
 */

/* routines-start */
/* routines-end */

/* boot ready */
mediator.emit('boot.ready');